version: "3"

services:
  migration:
    image: misskey/misskey:2023.12.0
    command: ["pnpm", "run", "init"]
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}/files:/misskey/files
      - ${PWD}/local.yml:/misskey/.config/default.yml
