apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: misskey
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    nodePort: 30080

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-misskey-config
  namespace: misskey
spec:
  storageClassName: misskey-config
  capacity:
    storage: 5Mi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 192.168.10.41
    path: /home/commojun/nfs/misskey/config

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-misskey-config
  namespace: misskey
spec:
  storageClassName: misskey-config
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-misskey-files
  namespace: misskey
spec:
  storageClassName: misskey-files
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 192.168.10.41
    path: /home/commojun/nfs/misskey/files

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-misskey-files
  namespace: misskey
spec:
  storageClassName: misskey-files
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: web-deployment
  namespace: misskey
  labels:
    deploy: web
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "75%"
      maxSurge: "50%"
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - pi31
                    - pi32
                    - pi33
      containers:
      - name: web
        image: misskey/misskey:13.11.3
        volumeMounts:
        - mountPath: /misskey/files
          name: misskey-files
        - mountPath: /misskey/.config
          name: misskey-config
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "2"
        command: ["pnpm", "run", "start"]
        readinessProbe:
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 600
          periodSeconds: 30
      volumes:
      - name: misskey-files
        persistentVolumeClaim:
          claimName: pvc-misskey-files
      - name: misskey-config
        persistentVolumeClaim:
          claimName: pvc-misskey-config
