url: https://domain/
db:
  host: db
  port: 5432
  db: misskey
  user: misskey
  pass: hogehoge
redis:
  host: redis
  port: 6379
id: 'aid'
port: 80

# Number of worker processes
clusterLimit: 1

# Job concurrency per worker
deliverJobConcurrency: 32
inboxJobConcurrency: 16

# Job rate limiter
deliverJobPerSec: 32
inboxJobPerSec: 16

# Job attempts
deliverJobMaxAttempts: 12
inboxJobMaxAttempts: 8
